# Generated by Django 3.2 on 2021-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('selectedtype', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Facebook_Account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('GooglePlus_Account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Instra_Account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Tweeter_Account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Language_u_know', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('check', models.CharField(blank=True, default='NO', max_length=10, null=True)),
                ('CDC_ckeck_email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Portfolio_Section1_Date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section1_Date_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section1_Main_Note_Keyword', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section1_Main_Note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section2_Date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section2_Date_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section2_Main_Note_Keyword', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section2_Main_Note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section3_Date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section3_Date_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section3_Main_Note_Keyword', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Portfolio_Section3_Main_Note', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'storeinfo',
            },
        ),
    ]
