# Generated by Django 3.2 on 2021-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='imagenow',
            field=models.ImageField(default='random.jpg', upload_to='Profile_image'),
        ),
    ]
