# Generated by Django 3.2 on 2021-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_userreg_your_expertise_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='About',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
